### ISSUE TITLE
Debian postinstall fail if there are more than one match in tar extract

### ISSUE THREAD

**Issue by aristella** [mmk2410/intellij-idea-ultimate#1]
Debian Postinstallation for version idea-intellij-ultimate-2017.2.5 script run the following command:

cd /opt
tar xf ideaIU-*

if there are more than one ideaIU files under /opt (for example ideaIU-15.0.1.tar.gz, ideaIU-2017.2.5.tar.gz), tar command expands to:

tar xvf ideaIU-15.0.1.tar.gz ideaIU-2017.2.5.tar.gz

Which breaks the idea-intellij-ultimate installation

**Comment by mmk2410** [comment]
Migrated to https://gitlab.com/mmk2410/intellij-idea-community/issues/5.
